app:
  name: telegram-bot-quiz
  version: v1


#mongodb
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  cache:
    jcache:
      config: classpath:ehcache.xml
  jackson:
    default-property-inclusion: NON_NULL
      
      
#logging
logging:
  level:
    org:
      springframework:
        data: debug

salt:
  one: uG4fV6xB7kA3yL7h
  two: ${SALT}
  
telegram:
  bot:
    username: ${TELEGRAM_BOT_UN}
    token: ${TELEGRAM_BOT_TOKEN}
    
trivia:
  host: https://opentdb.com  
  path:
    category: /api_category.php
    category_count: /api_count.php?category=
    token: /api_token.php?command=request
    questions: /api.php
 
schdlr:
  trivia:
    qstntypes: '0 0 */6 * * *'
